#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogVFXAgent, Log, All);

#if defined(VFXAGENTCORE_API)
	#define VFXAGENT_API VFXAGENTCORE_API
#elif defined(VFXAGENTNIAGARAMODULE_API)
	#define VFXAGENT_API VFXAGENTNIAGARAMODULE_API
#elif defined(VFXAGENTEDITOR_API)
	#define VFXAGENT_API VFXAGENTEDITOR_API
#else
	#define VFXAGENT_API
#endif